//  Generated by the swagger2objc.  DO NOT EDIT!
//  SIRequestKit.h
//  SIRequestKit
//
//  Copyright © {year} {company}. All rights reserved.
//

#import <Foundation/Foundation.h>

#ifndef _SIREQUESTKIT_
#define _SIREQUESTKIT_


#endif /* _SIREQUESTKIT_ */
