//
//  Generated by the swagger2objc.  DO NOT EDIT!
//  {class_name}.h
//  {project}
//
//  Copyright © {year} {company}. All rights reserved.
//

{import}#import <Foundation/Foundation.h>

@interface {class_name} : NSObject
{properties}
@end
