//
//  Generated by the swagger2objc.  DO NOT EDIT!
//  {class_name}.m
//  {project}
//
//  Copyright © {year} {company}. All rights reserved.
//

#import "{class_name}.h"

@implementation {class_name}
{container_mapping}{property_mapping}{response_class_body}
- (NSDictionary *)srk_config {
{srk_config}
}

@end
