//
//  Generated by the swagger2objc.  DO NOT EDIT!
//  {class_name}.h
//  {project}
//
//  Created by {author} on {date}.
//  Copyright © {year} {company}. All rights reserved.
//

#import <Foundation/Foundation.h>
{import}
@interface {class_name} : NSObject
{properties}
@end
