//
//  Generated by the swagger2objc.  DO NOT EDIT!
//  {module_name}.h
//  {project}
//
//  Copyright © {year} {company}. All rights reserved.
//

#ifndef {module_name}_h
#define {module_name}_h

{header}
#endif /* {module_name}_h */
