//
//  Generated by the swagger2objc.  DO NOT EDIT!
//  {class_name}.m
//  {project}
//
//  Created by {author} on {date}.
//  Copyright © {year} {company}. All rights reserved.
//

#import "{class_name}.h"

@implementation {class_name}
{container_mapping}
{property_mapping}
@end
